name: Java / Gradle CI Caller
run-name: Building with Gradle triggered via ${{ github.event_name }} by ${{ github.actor }}
on: [push]
jobs:
  call-build-workflow:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/build.yaml@master