run-name: ${{ github.actor }}
on:
  pull_request:
    types: [closed]
jobs:
  call-cleanup-workflow:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/cleanup-after-pull-request-closing.yaml@master
    with:
      repo-name: "address-check"
      branch-name: "${{ github.event.pull_request.head.ref }}"
    secrets: inherit