name: Continuous Deployment - Development
on:
  workflow_run:
    workflows: [Java / Gradle CI]
    branches: [development]
    types: [completed]

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Deploy Helm Umbrella Chart
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'build.yaml'
          repo: 'mehmetsalgar/fsm-akka-helm-umbrella-chart'
          ref: 'development'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
      - name: Prepare Environment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'prepare-environment.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: 'bitnami'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          #inputs: '"source-repo": "address-check", "version": "${{ env.SEMVER }}"'
