name: Continuous Deployment Caller - Pull Request
run-name: ${{ github.actor }}
on:
  pull_request:
    types: [opened]
    branches:
      - 'development'
jobs:
  call-continuous-deployment-workflow:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/continuous-deployment-pull-request.yaml@master
    with:
      repo-name: "address-check"
      branch-name: "${{ github.event.pull_request.head.ref }}"
    secrets: inherit
