name: Continuous Deployment - Development
on:
  workflow_run:
    workflows: [Java / Gradle CI]
    branches: [development]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: DoTemplate
        run: |
          echo 'Deploy Umbrella Chart for Service Pipeline'
          helmfile --version
      #- uses: actions/github-script@v6
      #  with:
      #    github-token: ${{ secrets.PERSONAL_TOKEN }}
      #    script: |
      #      await github.rest.actions.createWorkflowDispatch({
      #       owner: 'mehmetsalgar',
      #       repo: 'fsm-akka-helm-umbrella-chart',
      #       workflow_id: 'build.yaml',
      #       ref: 'development'
      #      })
      - name: Deploy Helm Umbrella Chart
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'build.yaml'
          repo: 'mehmetsalgar/fsm-akka-helm-umbrella-chart'
          ref: 'development'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
      - name: Prepare Environment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'build.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: 'master'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
