name: Release GA
run-name: Release GA triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-lastest
    steps:
      - name: Releasing
        run: |
          echo 'Releasing'
